Added ability to profile nested lists
moj-analytical-services/splink pull request #1074
Opened 2023-02-24 13:29 UTC by zslade

Addresses issue [#1034](https://github.com/moj-analytical-services/splink/issues/1034).

Can now supply nested lists to `linker.profile_columns()` to profile multiple columns alongside singular columns. This allows users to profile the multiple columns that make up a blocking rule.

This does not currently work for `sqlite`

2023-02-27 10:41 UTC, ADBond requested changes
I think something may be going amiss with the `NULL` handling here. Not sure exactly what, but if I save one of the new charts from `test_profile_data.py` (with a couple of additions) I get this:
![profile](https://user-images.githubusercontent.com/48208438/221541695-215b0ada-1faa-470d-8f59-9faa1998c67f.png)
which seems to suggest that in these cases the `NULL` values are being treated as blank strings, although they are handled correctly if you pass individual columns (not as a singleton array).

2023-02-28 21:43 UTC, ThomasHepworth commented on splink/profile_data.py
> +
Yup. The rebase didn't go to plan😳

2023-02-28 21:46 UTC, ThomasHepworth commented
Ta Andy. It's odd that the `NULL` handling has now decided to stop working.

You can see the old results in the issue I originally posted.

I'll take a look and see if I can figure it out.

2023-02-28 22:18 UTC, ThomasHepworth commented
@ADBond found the [issue](https://github.com/moj-analytical-services/splink/pull/1074/commits/3412205cfb2155d4a30fe9dbf130a7aec27dfa3b).

It was a slight error when the rebase happened.

2023-03-01 08:51 UTC, ADBond approved these changes
Looks good, working fine now 👍 . Seems there are just a couple of small issues with the imports in test file causing the linter check to fail, but happy for this to be merged once those are fixed.

2023-03-01 13:17 UTC, merged