Create Distance in KM Comparison library function
moj-analytical-services/splink pull request #1117
Opened 2023-03-12 20:20 UTC by RossKen

Based off #1038 and #1039 plus a couple of logging and docs edits

2023-03-13 15:16 UTC, ADBond requested changes
Looks good - and extended logging functionality useful. Just one point re: object/array columns, and a query about default values

2023-03-13 15:16 UTC, ADBond commented on tests/test_km_distance_level.py
> +
```suggestion
    print(
        cl.distance_in_km_at_thresholds(
            lat_col="latlong[0]", long_col="latlong[1]", km_thresholds=[1, 5, 10]
        ).as_dict()
    )
    print(
        cl.distance_in_km_at_thresholds(
            lat_col="ll['lat']", long_col="ll['long']", km_thresholds=[1, 5, 10]
        ).as_dict()
    )

@pytest.mark.parametrize(
    ("cll"),
    [
        pytest.param(clld, id="DuckDB Distance in KM cll simple run tests"),
        pytest.param(clls, id="Spark Distance in KM cll simple run tests"),
    ],
)
def test_simple_run_cll(cll):
    print(
        cll.distance_in_km_level(
            lat_col="lat", long_col="long", km_threshold=1
        ).as_dict()
    )
    print(
        cll.distance_in_km_level(
            lat_col="latlong[0]", long_col="latlong[1]", km_threshold=0.1
        ).as_dict()
    )
    print(
        cll.distance_in_km_level(
            lat_col="ll['lat']", long_col="ll['long']", km_threshold=10
        ).as_dict()
    )
```
Checks for using array/object columns - as things stand the `cll` version passes, but the new comparison code does not

2023-03-13 15:36 UTC, RossKen commented on splink/comparison_library.py
> +        include_exact_match_level=True,
Pushed

2023-03-13 17:24 UTC, RossKen commented on splink/comparison_library.py
> +        }
As discussed separately - using `InputColumn` on null level reveals an issue with `_sql_dialect` so we have agreed to leave this PR as is and deal with it separately.

2023-03-13 17:36 UTC, ADBond commented on splink/comparison_library.py
> +        }
Yep sounds good - might be worth commenting out the failing tests for the time being so as not to confuse matters if anyone else is branching of `master`, but I'll leave that up to you

2023-03-13 17:36 UTC, ADBond approved these changes

2023-03-14 09:12 UTC, RossKen commented on splink/comparison_library.py
> +        }
Yea, that's my bad. Commented out and pushed. Will merge when tests pass.

2023-03-14 09:12 UTC, RossKen commented on splink/comparison_library.py
> +        }
Thanks for all your help!

2023-03-14 09:23 UTC, merged