Releases dev guide
moj-analytical-services/splink pull request #1202
Opened 2023-04-25 15:01 UTC by RossKen

Given my ability to mess up releases - adding a dev guide to outline the steps for myself (and others)

I will update the image paths to master once this has been reviewed.

2023-04-25 19:52 UTC, ThomasHepworth commented on docs/dev_guides/changing_splink/releases.md
> +Splink is regularly updated with releases to add new features or bug fixes to the package.
Something on semantic versioning?

2023-04-25 19:52 UTC, ThomasHepworth commented on docs/dev_guides/changing_splink/releases.md
> +Splink is regularly updated with releases to add new features or bug fixes to the package.
A link is sufficient here.

2023-04-25 19:53 UTC, ThomasHepworth requested changes
Minor comments and then I'll approve.

2023-04-26 11:16 UTC, RossKen commented on docs/dev_guides/changing_splink/releases.md
> +![](https://raw.githubusercontent.com/moj-analytical-services/splink/master/docs/img/releases-tag.png))
The images? I have switched them to point at master (i.e. not this branch) for when it is merged in. Apologies, I should have left a comment to make that clear

2023-04-26 12:05 UTC, ThomasHepworth approved these changes

2023-04-26 12:05 UTC, merged