[WIP] String comparator charts
moj-analytical-services/splink pull request #1408
Opened 2023-07-06 16:45 UTC by samnlindsay

Improvements to string comparator charts. 

Still to do:
[] Improved docstrings
[] Figure out why Vega-Lite is complaining about the "mark" property in the JSON 🤷

2023-08-03 17:27 UTC, RossKen commented
@samnlindsay I will look at properly next week, but one immediate thing is that now we have fixed the rendering issue with the docs, we can get rid of the png files 🎉

2023-08-08 08:54 UTC, RossKen commented
Hey @samnlindsay I have pushed a couple of small changes when reviewing this:
- Rebase ontop of master
- Rerun string comparators notebook to use prettier charts (& remove pngs as they are no longer needed)
- Remove unused import flagged in lint

There are a couple more minor changes needed then I will approve:
- fix linting - it is saying about a `df` never being used
- warnings thrown by the function e.g.
![image](https://github.com/moj-analytical-services/splink/assets/26222179/8f50154e-6dfa-4176-8e11-48aae4fe2f04)

2023-08-08 08:55 UTC, RossKen requested changes
See above comment

2023-08-08 09:03 UTC, samnlindsay commented
The unused `df` isn't anything I've changed, it's to do with how we get data into duckdb:

```python
duckdb.connect()
df = pd.DataFrame(list)
duckdb.sql("select * from df").df()
```
But in this case df isn't referenced again.

2023-08-08 09:33 UTC, samnlindsay commented on splink/comparison_helpers.py
> +    df = pd.DataFrame(list)
Maybe it was, but by my reckoning the unchanged version shouldn't work:

```python
import duckdb
import pandas as pd

duckdb.connect()
pd.DataFrame([[1,2,3],["a","b","c"]])
duckdb.sql("""select * from df""")
```

2023-08-08 11:28 UTC, RossKen commented on splink/comparison_helpers.py
> +    df = pd.DataFrame(list)
Yea I get that, but it worked in the previous version and I'm not willing to spend more time on it now coming up with a better solution. So I have reverted the change and pushed

2023-08-08 11:28 UTC, RossKen approved these changes

2023-08-08 13:53 UTC, merged