Add completeness (by dataset) chart
moj-analytical-services/splink pull request #669
Opened 2022-07-25 09:51 UTC by samnlindsay

Motivated by [this PR](https://github.com/moj-analytical-services/data_linking/pull/236) that I repeatedly go back to just for the image that is really useful to understand the available data in the datasets being linked.

## Example with linked data
```
# For linked datasets, and a supplied list of column names
cols = [
    "forename1_std", 
    "surname_std", 
    "dob", 
    "pnc_id", 
    "cro_number", 
    "booking_no_arr", 
    "crn", 
    "asn_arr", 
    "ptiurn_arr", 
    "committal_date_arr", 
    "offence_ho_code_arr", 
    "postcode_unvalidated_arr"
]
linker.completeness_chart(cols=cols)
```
![image](https://user-images.githubusercontent.com/7570107/180749094-32f5cebc-afd2-4199-8f92-e4255570e3de.png)

## Example with demo dedupe-only
Less usefully, it does work for single datasets, where it is effectively an alternative to `missingness_chart`
```
# Added to 01_Exploratory_analysis.ipynb (splink_demos)
linker.completeness_chart()
```
![Screenshot 2022-07-25 at 10 50 25](https://user-images.githubusercontent.com/7570107/180749494-21a89c67-0f4e-404f-9801-0a4a870c6b35.png)

2022-07-25 10:44 UTC, Th368MoJ commented on splink/missingness.py
> +    df = linker._execute_sql_pipeline()
We have a wrapper for enqueue + execute if you're not queueing multiple statements.

```suggestion
    df = linker._enqueue_and_execute_sql_pipeline(
        sql, "__splink__df_all_column_completeness"
    )
```

2022-07-27 14:14 UTC, Th368MoJ reviewed
LGTM btw. I'll let Robin give the final thumbs up though.

2022-08-01 06:31 UTC, RobinL commented
Looks good.

Some suggestions here:
https://github.com/moj-analytical-services/splink/pull/677

And you've forgotten to commit the `completeness.json` chart spec!

2022-08-01 06:33 UTC, RobinL requested changes
Looks good.

Some suggestions here:
https://github.com/moj-analytical-services/splink/pull/677

And you've forgotten to commit the `completeness.json` chart spec!

2022-08-01 13:41 UTC, samnlindsay commented
> Looks good.
> 
> Some suggestions here: #677
> 
> And you've forgotten to commit the `completeness.json` chart spec!

Thanks, that's better than the (uncommitted) check for source dataset column that I used, and of course you have a method for the right columns :+1:

2022-08-01 17:07 UTC, RobinL commented
Looks good now.  Please could you remove the commented out code and then feel free to merge

![image](https://user-images.githubusercontent.com/2608005/182204493-f0924345-a41c-400f-975f-59ba9d920146.png)

2022-08-01 17:08 UTC, RobinL approved these changes

2022-08-01 17:14 UTC, merged